-- V1: Tablas base (MySQL)
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  correo_electronico VARCHAR(150) NOT NULL UNIQUE,
  contrasena VARCHAR(100) NOT NULL,
  rol VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS topicos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(200) NOT NULL UNIQUE,
  mensaje VARCHAR(255) NOT NULL UNIQUE,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'ABIERTO',
  autor VARCHAR(100) NOT NULL,
  curso VARCHAR(100) NOT NULL,
  respuestas INT DEFAULT 0
) ENGINE=InnoDB;

CREATE INDEX idx_topicos_fecha ON topicos(fecha_creacion);
